# -*- coding: utf-8 -*-
"""2ndAssignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7JkDrgkbojzvsaWJ8HqciAxY7UAKHqz
"""

participants = []
n = int(input("Enter number of tickets available: "))
    
for i in range(n):

    names = (input("Enter the name "+ str(i+1) + " :"))
 
    participants.append(names) 
     
print(participants)
import random
p=random.randint(0,n-1)
print("And the winner is:",participants[p])

