# -*- coding: utf-8 -*-
"""4th Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LXqxe5-otOZblSTjvGEp6VizCoCAicjw
"""

#to find prime no.
def Prime(n):
 m= 0
 if n>1:  
    for i in range(2,n):
     if (n%i)== 0:
      m = 1
      break
 if m ==1:
  return"non Prime"
 else:
  return "prime"      
n=int(input("Enter the number.:(Greater than 1)"))
Prime(n)

