# -*- coding: utf-8 -*-
"""YoutubeDownloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1paIiwLmWZUlmPGWiGsJui9ZKfakhOWaI
"""

!pip install pytube

from pytube import YouTube
url=input("Enter the Youtube Url to be downloaded: ")
video = YouTube(url)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Title of the Video~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print(video.title)
print("Wanna download Video Thumbnail here is it😁:")
print(video.thumbnail_url)
print("Downloading Video😎")
video = video.streams.get_highest_resolution()
video.download()

